services:
  - type: web
    name: sorare-card-coach
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_BACKEND_URL
        value: https://sorare-card-coach.onrender.com
      - key: VITE_OPENAI_API_KEY
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true
